[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.62.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

[[redirects]]
  from = "post/2020/02/06/how-to-calculate-contrasts-from-a-fitted-brms-model/"
  to = "https://mvuorre.github.io/blog/posts/2020-02-06-how-to-calculate-contrasts-from-a-fitted-brms-model/"
  force = true

[[redirects]]
  from = "post/2016/09/29/meta-analysis-is-a-special-case-of-bayesian-multilevel-modeling/"
  to = "https://mvuorre.github.io/blog/posts/2016-09-29-bayesian-meta-analysis/"
  force = true
